#PRÁCTICA DE NUMPY EN JUPYTER
**aquí se realizaran los ejercicios

In [8]:
import numpy as np
array = np.array([1,2,3,4,5])
print(array)
print(array[0])
print(type(array))
print(array *2)

[1 2 3 4 5]
1
<class 'numpy.ndarray'>
[ 2  4  6  8 10]


In [9]:
print(array.sum())
print(array.mean())
print(array.max())
print(array.min())
print(array.shape)

15
3.0
5
1
(5,)


In [46]:
matriz= np.array([[1,2,4],
                  [14,6,7]])
print(matriz)
print(matriz.shape)
print(matriz[0])
print(matriz[1,2])

[[ 1  2  4]
 [14  6  7]]
(2, 3)
[1 2 4]
7


#UNIDIMENSIONALES (5,)
#BIDIMENSIONAL (2,3) siendo el primer numero filas y el segundo columnas

#OPERACIONES CON MATRICES:
#AXIS 0 POR COLUMNAS Y AXIS 1 POR FILAS
#Porque el shape(2,4) el primero son las filas y el segundo las columnas
#si es por filas significa "muevete por filas" por tanto recorre las columnas

In [47]:
print(matriz.sum())
print(matriz.sum(axis=0))
print(matriz.sum(axis=1))
print(matriz.mean())

34
[15  8 11]
[ 7 27]
5.666666666666667


#INDEXING Y SLICING

In [48]:
print(matriz[0,1])
print(matriz[:, 1])
print(matriz[1,:])
print(matriz[0,0:3])
print(matriz[0:2, 0])
print(matriz[0:2, 1:3])

2
[2 6]
[14  6  7]
[1 2 4]
[ 1 14]
[[2 4]
 [6 7]]


In [49]:
print(np.eye(3))
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.random.rand(1,3))
print(np.random.randint(1,9, size=(3,3)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.12840599 0.32842245 0.61565518]]
[[5 7 4]
 [1 4 1]
 [7 8 6]]
